test_params:
  retriever: "colbert"
  eval_dataset: "nfcorpus"
  split: "test"
  model_name: "llama3"
  shadow_model_name: "llama3"
  gpu_id: 0
  attack_method: "mia"
  repeat_times: 1
  M: 1000
  N: 15
  top_k: 4
  seed: 12
  from_ckpt: true
  post_filter: true
