test_params:
  retriever: "gte"
  eval_dataset: "nfcorpus"
  split: "test"
  model_name: "llama3"
  shadow_model_name: "llama3"
  gpu_id: 0
  attack_method: "mia"
  repeat_times: 1
  M: 250
  N: 15
  top_k: 15
  seed: 12
  retrieve_k: 3
  from_ckpt: false
  post_filter: null # top or random or none 
