attack_config:
  M: 250
  N: 15
  attack_method: mia
  from_ckpt: true
  name: debug
  post_filter: null
  repeat_times: 1
  seed: 12
  top_k: 15
llm_config:
  gpu_id: 0
  model_config_path: null
  model_name: llama3
  shadow_model_name: llama3
rag_config:
  eval_dataset: trec-covid
  rerank_k: null
  reranker: null
  retrieve_k: 3
  retriever: bge
  split: test
