test_params:
  retriever: "colbert"
  eval_dataset: "trec-covid"
  split: "test"
  model_name: "llama3"
  shadow_model_name: "llama3"
  gpu_id: 0
  attack_method: "mia"
  repeat_times: 1
  M: 250
  N: 15
  top_k: 12
  retrieve_k: 3
  seed: 12
  from_ckpt: true
  post_filter: 'top' # top or random or none 
